/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RoboAdvisorAdmin.java
 *
 * Created on Nov 7, 2011, 7:40:51 PM
 */
package robotest2;

import java.awt.CardLayout;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kevin
 */
public class RoboAdvisorAdmin extends javax.swing.JFrame {

    RoboController roboControl = new RoboController();
    // The List Models for the Template admin area
    DefaultListModel scienceModel = new DefaultListModel();
    DefaultListModel mathStatsModel = new DefaultListModel();
    DefaultListModel compsciModel = new DefaultListModel();
    DefaultListModel humanitiesModel = new DefaultListModel();
    DefaultListModel socialModel = new DefaultListModel();
    DefaultListModel mathModel = new DefaultListModel();
    DefaultListModel generalModel = new DefaultListModel();
    DefaultListModel electiveModel = new DefaultListModel();

    /** Creates new form RoboAdvisorAdmin */
    public RoboAdvisorAdmin() {
        initComponents();
        Template.currentTemplates = roboControl.GetTemplatesFromDB();

        // For some reason this is the only place that
        // it will let me load the template values in.
        for (String s : Template.templateNameList) {
            jcomboTemplate.addItem(s);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDays = new javax.swing.ButtonGroup();
        buttonGroupSemester = new javax.swing.ButtonGroup();
        jPanelAdmin = new javax.swing.JPanel();
        jPanelAdminMain = new javax.swing.JPanel();
        jbtnCourseAdmin = new javax.swing.JButton();
        jbtnTemplateAdmin = new javax.swing.JButton();
        jlblAdminTitle = new javax.swing.JLabel();
        jlblAdminDesc = new javax.swing.JLabel();
        jPanelAdminCourse = new javax.swing.JPanel();
        jlblCourseCreationTitle = new javax.swing.JLabel();
        jlblCourseName = new javax.swing.JLabel();
        jtxtCourseName = new javax.swing.JTextField();
        jlblCourseTitle = new javax.swing.JLabel();
        jtxtCourseTitle = new javax.swing.JTextField();
        jlblCRN = new javax.swing.JLabel();
        jtxtCRN = new javax.swing.JTextField();
        jlblDays = new javax.swing.JLabel();
        jradMWF = new javax.swing.JRadioButton();
        jradTR = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jcomboTime = new javax.swing.JComboBox();
        jlblSemester = new javax.swing.JLabel();
        jradSeptDec = new javax.swing.JRadioButton();
        jradJanMay = new javax.swing.JRadioButton();
        jlblProfessor = new javax.swing.JLabel();
        jtxtProfessor = new javax.swing.JTextField();
        jlblDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtDescription = new javax.swing.JTextArea();
        jbtnSaveCourse = new javax.swing.JButton();
        jbtnClearCourse = new javax.swing.JButton();
        jbtnEditCourse = new javax.swing.JButton();
        jbtnDeleteCourse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        NewTableModel model = new NewTableModel();
        model.addColumn("Req");
        model.addColumn("Name");
        model.addColumn("Title");
        model.setRowCount(Course.CourseCatalog.size());
        jtblPrereq = new JTable(model);
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel();
        for(int i = 0;i < Course.CourseCatalog.size();i++){
            comboModel.addElement(Course.CourseCatalog.get(i).getCourseName());
        }
        jcomboEdit = new JComboBox(comboModel);
        jbtnCourseBack = new javax.swing.JButton();
        jPanelAdminTemplate = new javax.swing.JPanel();
        jlblTemplateTitle = new javax.swing.JLabel();
        jlblCourse = new javax.swing.JLabel();
        DefaultComboBoxModel templateModel = new DefaultComboBoxModel();
        for(int i = 0;i < Course.CourseCatalog.size();i++){
            templateModel.addElement(Course.CourseCatalog.get(i).getCourseName());
        }
        jcomboCourse = new JComboBox(templateModel);
        jlblCategory = new javax.swing.JLabel();
        jcomboCategory = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlistScience = new JList(scienceModel);
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlistMathStats = new JList(mathStatsModel);
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jlistCompsci = new JList(compsciModel);
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jlistHumanities = new JList(humanitiesModel);
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jlistSocial = new JList(socialModel);
        jLabel8 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jlistMath = new JList(mathModel);
        jLabel9 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jlistGeneral = new JList(generalModel);
        jLabel10 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jlistElectives = new JList(electiveModel);
        jbtnAddTemplate = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        DefaultComboBoxModel templateSelectModel = new DefaultComboBoxModel();
        jcomboTemplate = new JComboBox(templateSelectModel);
        jbtnTemplateSelect = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jtxtTemplateName = new javax.swing.JTextField();
        jbtnTemplateBack = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(robotest2.RoboTest2App.class).getContext().getResourceMap(RoboAdvisorAdmin.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanelAdmin.setName("jPanelAdmin"); // NOI18N
        jPanelAdmin.setPreferredSize(new java.awt.Dimension(1023, 684));
        jPanelAdmin.setLayout(new java.awt.CardLayout());

        jPanelAdminMain.setName("jPanelAdminMain"); // NOI18N

        jbtnCourseAdmin.setText(resourceMap.getString("jbtnCourseAdmin.text")); // NOI18N
        jbtnCourseAdmin.setName("jbtnCourseAdmin"); // NOI18N
        jbtnCourseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCourseAdminActionPerformed(evt);
            }
        });

        jbtnTemplateAdmin.setText(resourceMap.getString("jbtnTemplateAdmin.text")); // NOI18N
        jbtnTemplateAdmin.setName("jbtnTemplateAdmin"); // NOI18N
        jbtnTemplateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTemplateAdminActionPerformed(evt);
            }
        });

        jlblAdminTitle.setFont(resourceMap.getFont("jlblAdminTitle.font")); // NOI18N
        jlblAdminTitle.setText(resourceMap.getString("jlblAdminTitle.text")); // NOI18N
        jlblAdminTitle.setName("jlblAdminTitle"); // NOI18N

        jlblAdminDesc.setText(resourceMap.getString("jlblAdminDesc.text")); // NOI18N
        jlblAdminDesc.setName("jlblAdminDesc"); // NOI18N

        javax.swing.GroupLayout jPanelAdminMainLayout = new javax.swing.GroupLayout(jPanelAdminMain);
        jPanelAdminMain.setLayout(jPanelAdminMainLayout);
        jPanelAdminMainLayout.setHorizontalGroup(
            jPanelAdminMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminMainLayout.createSequentialGroup()
                .addGroup(jPanelAdminMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdminMainLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jbtnCourseAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                        .addGap(84, 84, 84)
                        .addComponent(jbtnTemplateAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                        .addGap(189, 189, 189))
                    .addGroup(jPanelAdminMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblAdminDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE))
                    .addGroup(jPanelAdminMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblAdminTitle)))
                .addContainerGap())
        );
        jPanelAdminMainLayout.setVerticalGroup(
            jPanelAdminMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblAdminTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblAdminDesc)
                .addGap(65, 65, 65)
                .addGroup(jPanelAdminMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCourseAdmin)
                    .addComponent(jbtnTemplateAdmin))
                .addContainerGap(531, Short.MAX_VALUE))
        );

        jPanelAdmin.add(jPanelAdminMain, "card2");

        jPanelAdminCourse.setName("jPanelAdminCourse"); // NOI18N

        jlblCourseCreationTitle.setFont(resourceMap.getFont("jlblCourseCreationTitle.font")); // NOI18N
        jlblCourseCreationTitle.setText(resourceMap.getString("jlblCourseCreationTitle.text")); // NOI18N
        jlblCourseCreationTitle.setName("jlblCourseCreationTitle"); // NOI18N

        jlblCourseName.setText(resourceMap.getString("jlblCourseName.text")); // NOI18N
        jlblCourseName.setToolTipText(resourceMap.getString("jlblCourseName.toolTipText")); // NOI18N
        jlblCourseName.setName("jlblCourseName"); // NOI18N

        jtxtCourseName.setText(resourceMap.getString("jtxtCourseName.text")); // NOI18N
        jtxtCourseName.setName("jtxtCourseName"); // NOI18N

        jlblCourseTitle.setText(resourceMap.getString("jlblCourseTitle.text")); // NOI18N
        jlblCourseTitle.setName("jlblCourseTitle"); // NOI18N

        jtxtCourseTitle.setText(resourceMap.getString("jtxtCourseTitle.text")); // NOI18N
        jtxtCourseTitle.setName("jtxtCourseTitle"); // NOI18N

        jlblCRN.setText(resourceMap.getString("jlblCRN.text")); // NOI18N
        jlblCRN.setName("jlblCRN"); // NOI18N

        jtxtCRN.setText(resourceMap.getString("jtxtCRN.text")); // NOI18N
        jtxtCRN.setName("jtxtCRN"); // NOI18N

        jlblDays.setText(resourceMap.getString("jlblDays.text")); // NOI18N
        jlblDays.setName("jlblDays"); // NOI18N

        buttonGroupDays.add(jradMWF);
        jradMWF.setText(resourceMap.getString("jradMWF.text")); // NOI18N
        jradMWF.setName("jradMWF"); // NOI18N

        buttonGroupDays.add(jradTR);
        jradTR.setText(resourceMap.getString("jradTR.text")); // NOI18N
        jradTR.setName("jradTR"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jcomboTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8:30 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:30 AM", "12:30 PM", "1:00 PM", "1:30 PM", "2:30 PM", "3:30 PM", "4:00 PM", "4:30 PM", "5:30 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:30 PM", "9:30 PM" }));
        jcomboTime.setName("jcomboTime"); // NOI18N

        jlblSemester.setText(resourceMap.getString("jlblSemester.text")); // NOI18N
        jlblSemester.setName("jlblSemester"); // NOI18N

        buttonGroupSemester.add(jradSeptDec);
        jradSeptDec.setText(resourceMap.getString("jradSeptDec.text")); // NOI18N
        jradSeptDec.setName("jradSeptDec"); // NOI18N

        buttonGroupSemester.add(jradJanMay);
        jradJanMay.setText(resourceMap.getString("jradJanMay.text")); // NOI18N
        jradJanMay.setName("jradJanMay"); // NOI18N

        jlblProfessor.setText(resourceMap.getString("jlblProfessor.text")); // NOI18N
        jlblProfessor.setName("jlblProfessor"); // NOI18N

        jtxtProfessor.setText(resourceMap.getString("jtxtProfessor.text")); // NOI18N
        jtxtProfessor.setName("jtxtProfessor"); // NOI18N

        jlblDescription.setText(resourceMap.getString("jlblDescription.text")); // NOI18N
        jlblDescription.setName("jlblDescription"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jtxtDescription.setColumns(20);
        jtxtDescription.setRows(5);
        jtxtDescription.setWrapStyleWord(true);
        jtxtDescription.setName("jtxtDescription"); // NOI18N
        jScrollPane1.setViewportView(jtxtDescription);

        jbtnSaveCourse.setText(resourceMap.getString("jbtnSaveCourse.text")); // NOI18N
        jbtnSaveCourse.setName("jbtnSaveCourse"); // NOI18N
        jbtnSaveCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveCourseActionPerformed(evt);
            }
        });

        jbtnClearCourse.setText(resourceMap.getString("jbtnClearCourse.text")); // NOI18N
        jbtnClearCourse.setName("jbtnClearCourse"); // NOI18N
        jbtnClearCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearCourseActionPerformed(evt);
            }
        });

        jbtnEditCourse.setText(resourceMap.getString("jbtnEditCourse.text")); // NOI18N
        jbtnEditCourse.setName("jbtnEditCourse"); // NOI18N
        jbtnEditCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditCourseActionPerformed(evt);
            }
        });

        jbtnDeleteCourse.setText(resourceMap.getString("jbtnDeleteCourse.text")); // NOI18N
        jbtnDeleteCourse.setName("jbtnDeleteCourse"); // NOI18N
        jbtnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteCourseActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jtblPrereq.setModel(model);
        jtblPrereq.setName("jtblPrereq"); // NOI18N
        jtblPrereq.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jtblPrereq);

        jcomboEdit.setModel(comboModel);
        jcomboEdit.setName("jcomboEdit"); // NOI18N

        jbtnCourseBack.setText(resourceMap.getString("jbtnCourseBack.text")); // NOI18N
        jbtnCourseBack.setName("jbtnCourseBack"); // NOI18N
        jbtnCourseBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCourseBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdminCourseLayout = new javax.swing.GroupLayout(jPanelAdminCourse);
        jPanelAdminCourse.setLayout(jPanelAdminCourseLayout);
        jPanelAdminCourseLayout.setHorizontalGroup(
            jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCourseCreationTitle)
                    .addGroup(jPanelAdminCourseLayout.createSequentialGroup()
                        .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblCourseName)
                            .addComponent(jlblCourseTitle)
                            .addComponent(jlblCRN)
                            .addComponent(jlblDays)
                            .addComponent(jLabel1)
                            .addComponent(jlblSemester)
                            .addComponent(jlblProfessor)
                            .addComponent(jlblDescription))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelAdminCourseLayout.createSequentialGroup()
                                .addComponent(jbtnSaveCourse)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnDeleteCourse)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnClearCourse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnCourseBack))
                            .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelAdminCourseLayout.createSequentialGroup()
                                    .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanelAdminCourseLayout.createSequentialGroup()
                                            .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jcomboTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanelAdminCourseLayout.createSequentialGroup()
                                                    .addComponent(jradMWF)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jradTR))
                                                .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jtxtCRN)
                                                    .addComponent(jtxtCourseTitle)
                                                    .addComponent(jtxtCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                                .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jtxtProfessor, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAdminCourseLayout.createSequentialGroup()
                                                        .addComponent(jradSeptDec)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jradJanMay))))
                                            .addGap(108, 108, 108))
                                        .addComponent(jLabel2))
                                    .addGap(41, 41, 41)
                                    .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanelAdminCourseLayout.createSequentialGroup()
                                            .addComponent(jcomboEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jbtnEditCourse))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        jPanelAdminCourseLayout.setVerticalGroup(
            jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCourseCreationTitle)
                    .addComponent(jbtnEditCourse)
                    .addComponent(jcomboEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdminCourseLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCourseName)
                            .addComponent(jtxtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCourseTitle)
                            .addComponent(jtxtCourseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCRN)
                            .addComponent(jtxtCRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblDays)
                            .addComponent(jradMWF)
                            .addComponent(jradTR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jcomboTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblSemester)
                            .addComponent(jradSeptDec)
                            .addComponent(jradJanMay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblProfessor)
                            .addComponent(jtxtProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblDescription)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdminCourseLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAdminCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnSaveCourse)
                            .addComponent(jbtnDeleteCourse)
                            .addComponent(jbtnClearCourse)))
                    .addGroup(jPanelAdminCourseLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtnCourseBack)))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jPanelAdmin.add(jPanelAdminCourse, "card3");
        int iter = 0;
        for(Course c: Course.CourseCatalog){
            jtblPrereq.setValueAt(c.getCourseName(), iter, 1);
            jtblPrereq.setValueAt(c.getCourseTitle(), iter, 2);

            iter++;
        }

        jPanelAdminTemplate.setName("jPanelAdminTemplate"); // NOI18N

        jlblTemplateTitle.setFont(resourceMap.getFont("jlblTemplateTitle.font")); // NOI18N
        jlblTemplateTitle.setText(resourceMap.getString("jlblTemplateTitle.text")); // NOI18N
        jlblTemplateTitle.setName("jlblTemplateTitle"); // NOI18N

        jlblCourse.setText(resourceMap.getString("jlblCourse.text")); // NOI18N
        jlblCourse.setName("jlblCourse"); // NOI18N

        jcomboCourse.setModel(templateModel);
        jcomboCourse.setName("jcomboCourse"); // NOI18N

        jlblCategory.setText(resourceMap.getString("jlblCategory.text")); // NOI18N
        jlblCategory.setName("jlblCategory"); // NOI18N

        jcomboCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Natural Science", "Math and Stats", "Computer Science", "Humanities Writing", "Social Science", "Cognate Math", "General", "Elective" }));
        jcomboCategory.setName("jcomboCategory"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jlistScience.setModel(scienceModel);
        jlistScience.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlistScience.setName("jlistScience"); // NOI18N
        jScrollPane3.setViewportView(jlistScience);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        jlistMathStats.setModel(mathStatsModel);
        jlistMathStats.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlistMathStats.setName("jlistMathStats"); // NOI18N
        jScrollPane4.setViewportView(jlistMathStats);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        jlistCompsci.setModel(compsciModel);
        jlistCompsci.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlistCompsci.setName("jlistCompsci"); // NOI18N
        jScrollPane5.setViewportView(jlistCompsci);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jScrollPane6.setName("jScrollPane6"); // NOI18N

        jlistHumanities.setModel(humanitiesModel);
        jlistHumanities.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlistHumanities.setName("jlistHumanities"); // NOI18N
        jScrollPane6.setViewportView(jlistHumanities);

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jScrollPane7.setName("jScrollPane7"); // NOI18N

        jlistSocial.setModel(socialModel);
        jlistSocial.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlistSocial.setName("jlistSocial"); // NOI18N
        jScrollPane7.setViewportView(jlistSocial);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jScrollPane8.setName("jScrollPane8"); // NOI18N

        jlistMath.setModel(mathModel);
        jlistMath.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlistMath.setName("jlistMath"); // NOI18N
        jScrollPane8.setViewportView(jlistMath);

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jScrollPane9.setName("jScrollPane9"); // NOI18N

        jlistGeneral.setModel(generalModel);
        jlistGeneral.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlistGeneral.setName("jlistGeneral"); // NOI18N
        jScrollPane9.setViewportView(jlistGeneral);

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jScrollPane10.setName("jScrollPane10"); // NOI18N

        jlistElectives.setModel(electiveModel);
        jlistElectives.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlistElectives.setName("jlistElectives"); // NOI18N
        jScrollPane10.setViewportView(jlistElectives);

        jbtnAddTemplate.setText(resourceMap.getString("jbtnAddTemplate.text")); // NOI18N
        jbtnAddTemplate.setName("jbtnAddTemplate"); // NOI18N
        jbtnAddTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddTemplateActionPerformed(evt);
            }
        });

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jcomboTemplate.setMaximumRowCount(100);
        jcomboTemplate.setModel(templateSelectModel);
        jcomboTemplate.setName("jcomboTemplate"); // NOI18N

        jbtnTemplateSelect.setText(resourceMap.getString("jbtnTemplateSelect.text")); // NOI18N
        jbtnTemplateSelect.setName("jbtnTemplateSelect"); // NOI18N
        jbtnTemplateSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTemplateSelectActionPerformed(evt);
            }
        });

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jtxtTemplateName.setText(resourceMap.getString("jtxtTemplateName.text")); // NOI18N
        jtxtTemplateName.setName("jtxtTemplateName"); // NOI18N

        jbtnTemplateBack.setText(resourceMap.getString("jbtnTemplateBack.text")); // NOI18N
        jbtnTemplateBack.setName("jbtnTemplateBack"); // NOI18N
        jbtnTemplateBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTemplateBackActionPerformed(evt);
            }
        });

        jbtnClear.setText(resourceMap.getString("jbtnClear.text")); // NOI18N
        jbtnClear.setName("jbtnClear"); // NOI18N
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdminTemplateLayout = new javax.swing.GroupLayout(jPanelAdminTemplate);
        jPanelAdminTemplate.setLayout(jPanelAdminTemplateLayout);
        jPanelAdminTemplateLayout.setHorizontalGroup(
            jPanelAdminTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdminTemplateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdminTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAdminTemplateLayout.createSequentialGroup()
                        .addComponent(jlblTemplateTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                        .addGap(54, 54, 54))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addGroup(jPanelAdminTemplateLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(jbtnAddTemplate))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAdminTemplateLayout.createSequentialGroup()
                        .addComponent(jlblCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcomboCategory, 0, 371, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAdminTemplateLayout.createSequentialGroup()
                        .addGroup(jPanelAdminTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jlblCourse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAdminTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtTemplateName, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                            .addComponent(jcomboCourse, 0, 368, Short.MAX_VALUE)
                            .addComponent(jcomboTemplate, 0, 368, Short.MAX_VALUE)))
                    .addComponent(jbtnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnTemplateSelect)
                .addGap(67, 67, 67)
                .addGroup(jPanelAdminTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnTemplateBack)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdminTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAdminTemplateLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelAdminTemplateLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelAdminTemplateLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelAdminTemplateLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAdminTemplateLayout.setVerticalGroup(
            jPanelAdminTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminTemplateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTemplateTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdminTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdminTemplateLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanelAdminTemplateLayout.createSequentialGroup()
                        .addGroup(jPanelAdminTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcomboTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jbtnTemplateSelect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAdminTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTemplateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAdminTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcomboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblCourse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAdminTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCategory)
                            .addComponent(jcomboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAdminTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnAddTemplate)
                            .addGroup(jPanelAdminTemplateLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)))))
                .addGroup(jPanelAdminTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdminTemplateLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdminTemplateLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdminTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTemplateBack)
                    .addComponent(jbtnClear))
                .addContainerGap())
        );

        jPanelAdmin.add(jPanelAdminTemplate, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        jtxtTemplateName.setText("");
        ClearTemplate();
    }//GEN-LAST:event_jbtnClearActionPerformed

    /**
     *
     * @author Kevin
     */
    private void jbtnCourseAdminActionPerformed(java.awt.event.ActionEvent evt) {

        // Switches to the Course Admin screen
        CardLayout cl = (CardLayout) (jPanelAdmin.getLayout());
        cl.show(jPanelAdmin, "card3");

    }

    /**
     *
     * @author Kevin
     */
    private void jbtnTemplateAdminActionPerformed(java.awt.event.ActionEvent evt) {
        // Switches to the Course Template screen
        CardLayout cl = (CardLayout) (jPanelAdmin.getLayout());
        cl.show(jPanelAdmin, "card4");
    }

    /**
     *
     * @author Kevin
     */
    private void jbtnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {
        int CRN = Integer.parseInt(jtxtCRN.getText());
        int startTime = 830;

        if (jcomboTime.getSelectedItem().toString().equals("8:30 AM")) {
            startTime = 830;
        }
        if (jcomboTime.getSelectedItem().toString().equals("9:30 AM")) {
            startTime = 930;
        }
        if (jcomboTime.getSelectedItem().toString().equals("10:00 AM")) {
            startTime = 1000;
        }
        if (jcomboTime.getSelectedItem().toString().equals("10:30 AM")) {
            startTime = 1030;
        }
        if (jcomboTime.getSelectedItem().toString().equals("11:30 AM")) {
            startTime = 1130;
        }
        if (jcomboTime.getSelectedItem().toString().equals("12:30 PM")) {
            startTime = 1230;
        }
        if (jcomboTime.getSelectedItem().toString().equals("1:00 PM")) {
            startTime = 1300;
        }
        if (jcomboTime.getSelectedItem().toString().equals("1:30 PM")) {
            startTime = 1330;
        }
        if (jcomboTime.getSelectedItem().toString().equals("2:30 PM")) {
            startTime = 1430;
        }
        if (jcomboTime.getSelectedItem().toString().equals("3:30 PM")) {
            startTime = 1530;
        }
        if (jcomboTime.getSelectedItem().toString().equals("4:00 PM")) {
            startTime = 1600;
        }
        if (jcomboTime.getSelectedItem().toString().equals("4:30 PM")) {
            startTime = 1630;
        }
        if (jcomboTime.getSelectedItem().toString().equals("5:30 PM")) {
            startTime = 1730;
        }
        if (jcomboTime.getSelectedItem().toString().equals("6:30 PM")) {
            startTime = 1830;
        }
        if (jcomboTime.getSelectedItem().toString().equals("7:00 PM")) {
            startTime = 1900;
        }
        if (jcomboTime.getSelectedItem().toString().equals("7:30 PM")) {
            startTime = 1930;
        }
        if (jcomboTime.getSelectedItem().toString().equals("8:30 PM")) {
            startTime = 2030;
        }
        if (jcomboTime.getSelectedItem().toString().equals("9:30 PM")) {
            startTime = 2130;
        }

        Course newCourse = new Course();
        newCourse.setCourseName(jtxtCourseName.getText());
        newCourse.setCourseTitle(jtxtCourseTitle.getText());
        newCourse.setCrn(CRN);

        if (jradMWF.isSelected()) {
            newCourse.setDays("MWF");
        } else {
            newCourse.setDays("TR");
        }

        if (jradSeptDec.isSelected()) {
            newCourse.setSemester(1);
        } else {
            newCourse.setSemester(2);
        }

        newCourse.setProfessor(jtxtProfessor.getText());
        newCourse.setDescription(jtxtDescription.getText());
        newCourse.setStartTime(startTime);

        roboControl.RemoveCourseFromDB(newCourse);

        List<Prereq> dbPrereqs = roboControl.GetPrereqsFromDB(newCourse.getCourseName());

        for (Prereq p : dbPrereqs) {
            roboControl.RemovePrereqFromDB(p);
        }
    }

    /**
     *
     * @author Kevin
     */
    private void jbtnSaveCourseActionPerformed(java.awt.event.ActionEvent evt) {

        int CRN = Integer.parseInt(jtxtCRN.getText());
        int startTime = 830;

        if (jcomboTime.getSelectedItem().toString().equals("8:30 AM")) {
            startTime = 830;
        }
        if (jcomboTime.getSelectedItem().toString().equals("9:30 AM")) {
            startTime = 930;
        }
        if (jcomboTime.getSelectedItem().toString().equals("10:00 AM")) {
            startTime = 1000;
        }
        if (jcomboTime.getSelectedItem().toString().equals("10:30 AM")) {
            startTime = 1030;
        }
        if (jcomboTime.getSelectedItem().toString().equals("11:30 AM")) {
            startTime = 1130;
        }
        if (jcomboTime.getSelectedItem().toString().equals("12:30 PM")) {
            startTime = 1230;
        }
        if (jcomboTime.getSelectedItem().toString().equals("1:00 PM")) {
            startTime = 1300;
        }
        if (jcomboTime.getSelectedItem().toString().equals("1:30 PM")) {
            startTime = 1330;
        }
        if (jcomboTime.getSelectedItem().toString().equals("2:30 PM")) {
            startTime = 1430;
        }
        if (jcomboTime.getSelectedItem().toString().equals("3:30 PM")) {
            startTime = 1530;
        }
        if (jcomboTime.getSelectedItem().toString().equals("4:00 PM")) {
            startTime = 1600;
        }
        if (jcomboTime.getSelectedItem().toString().equals("4:30 PM")) {
            startTime = 1630;
        }
        if (jcomboTime.getSelectedItem().toString().equals("5:30 PM")) {
            startTime = 1730;
        }
        if (jcomboTime.getSelectedItem().toString().equals("6:30 PM")) {
            startTime = 1830;
        }
        if (jcomboTime.getSelectedItem().toString().equals("7:00 PM")) {
            startTime = 1900;
        }
        if (jcomboTime.getSelectedItem().toString().equals("7:30 PM")) {
            startTime = 1930;
        }
        if (jcomboTime.getSelectedItem().toString().equals("8:30 PM")) {
            startTime = 2030;
        }
        if (jcomboTime.getSelectedItem().toString().equals("9:30 PM")) {
            startTime = 2130;
        }

        Course newCourse = new Course();
        newCourse.setCourseName(jtxtCourseName.getText());
        newCourse.setCourseTitle(jtxtCourseTitle.getText());
        newCourse.setCrn(CRN);

        if (jradMWF.isSelected()) {
            newCourse.setDays("MWF");
        } else {
            newCourse.setDays("TR");
        }

        if (jradSeptDec.isSelected()) {
            newCourse.setSemester(1);
        } else {
            newCourse.setSemester(2);
        }

        newCourse.setProfessor(jtxtProfessor.getText());
        newCourse.setDescription(jtxtDescription.getText());
        newCourse.setStartTime(startTime);


        List dbPrereqs = roboControl.GetPrereqsFromDB(jtxtCourseName.getText());
        List tablePrereqs = new LinkedList();

        // This code grabs the values from the table and inserts the corresponding
        // entries into the transcript.
        String colName = "";
        Boolean colChecked = false;

        for (int i = 0; i < Course.CourseCatalog.size(); i++) {
            Prereq newPrereq = new Prereq(jtxtCourseName.getText(), (String) colName);
            colChecked = (Boolean) jtblPrereq.getValueAt(i, 0);
            colName = (String) jtblPrereq.getValueAt(i, 1);

            newPrereq.setCourseName(jtxtCourseName.getText());
            newPrereq.setPrereq((String) colName);

            if (colChecked) {
                tablePrereqs.add(newPrereq);
                System.out.println("In colChecked = true!");
                if (!dbPrereqs.contains(newPrereq)) {
                    System.out.println("In colChecked = true and add the prereq!");
                    roboControl.AddPrereqToDB(new Prereq(jtxtCourseName.getText(), (String) colName));
                }
            } else {
                System.out.println("In else statement: courseName: " + newPrereq.getCourseName() + "prereq: " + newPrereq.getPrereq());
                roboControl.RemovePrereqFromDB(newPrereq);
                colChecked = false;
            }

            System.out.println("<End Iteration>");
        }
        if (!Course.CourseCatalog.contains(newCourse)) {
            roboControl.AddCourseToDB(newCourse);
        } else {
            roboControl.MergeCourseToDB(newCourse);
        }

    }

    /**
     *
     * @author Kevin
     */
    private void jbtnClearCourseActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtCourseName.setText("");
        jtxtCourseTitle.setText("");
        jtxtCRN.setText("");
        jradMWF.setSelected(false);
        jradSeptDec.setSelected(false);
        jtxtProfessor.setText("");
        jtxtDescription.setText("");
        jcomboTime.setSelectedIndex(0);

        // Resets the checkboxes in the table
        for (int i = 0; i < Course.CourseCatalog.size(); i++) {
            jtblPrereq.setValueAt(new Boolean(false), i, 0);
        }
    }

    /**
     *
     * @author Kevin
     */
    private void jbtnEditCourseActionPerformed(java.awt.event.ActionEvent evt) {
        Course newCourse = new Course();
        List<Prereq> results = new LinkedList<Prereq>();

        newCourse = roboControl.GetCourseFromDB((String) jcomboEdit.getSelectedItem());
        results = roboControl.GetPrereqsFromDB((String) jcomboEdit.getSelectedItem());

        // Resets the checkboxes in the table
        for (int i = 0; i < Course.CourseCatalog.size(); i++) {
            jtblPrereq.setValueAt(false, i, 0);
        }

        for (Prereq p : results) {
            for (int i = 0; i < Course.CourseCatalog.size(); i++) {
                if (jtblPrereq.getValueAt(i, 1).equals(p.getPrereq())) {
                    jtblPrereq.setValueAt(true, i, 0);
                }
            }
        }

        jtxtCourseName.setText(newCourse.getCourseName());
        jtxtCourseTitle.setText(newCourse.getCourseTitle());
        jtxtCRN.setText(newCourse.getCrn().toString());
        if (newCourse.getDays().equals("MWF")) {
            jradMWF.setSelected(true);
        } else {
            jradTR.setSelected(true);
        }
        if (newCourse.getSemester() == 1) {
            jradSeptDec.setSelected(true);
        } else {
            jradJanMay.setSelected(true);
        }
        jtxtProfessor.setText(newCourse.getProfessor());
        jtxtDescription.setText(newCourse.getDescription());

        if (newCourse.getStartTime() == 830) {
            jcomboTime.setSelectedItem("8:30 AM");
        }
        if (newCourse.getStartTime() == 930) {
            jcomboTime.setSelectedItem("9:30 AM");
        }
        if (newCourse.getStartTime() == 1000) {
            jcomboTime.setSelectedItem("10:00 AM");
        }
        if (newCourse.getStartTime() == 1030) {
            jcomboTime.setSelectedItem("10:30 AM");
        }
        if (newCourse.getStartTime() == 1130) {
            jcomboTime.setSelectedItem("11:30 AM");
        }
        if (newCourse.getStartTime() == 1230) {
            jcomboTime.setSelectedItem("12:30 PM");
        }
        if (newCourse.getStartTime() == 1300) {
            jcomboTime.setSelectedItem("1:00 PM");
        }
        if (newCourse.getStartTime() == 1330) {
            jcomboTime.setSelectedItem("1:30 PM");
        }
        if (newCourse.getStartTime() == 1430) {
            jcomboTime.setSelectedItem("2:30 PM");
        }
        if (newCourse.getStartTime() == 1530) {
            jcomboTime.setSelectedItem("3:30 PM");
        }
        if (newCourse.getStartTime() == 1600) {
            jcomboTime.setSelectedItem("4:00 PM");
        }
        if (newCourse.getStartTime() == 1630) {
            jcomboTime.setSelectedItem("4:30 PM");
        }
        if (newCourse.getStartTime() == 1730) {
            jcomboTime.setSelectedItem("5:30 PM");
        }
        if (newCourse.getStartTime() == 1830) {
            jcomboTime.setSelectedItem("6:30 PM");
        }
        if (newCourse.getStartTime() == 1900) {
            jcomboTime.setSelectedItem("7:00 PM");
        }
        if (newCourse.getStartTime() == 1930) {
            jcomboTime.setSelectedItem("7:30 PM");
        }
        if (newCourse.getStartTime() == 2030) {
            jcomboTime.setSelectedItem("8:30 PM");
        }
        if (newCourse.getStartTime() == 2130) {
            jcomboTime.setSelectedItem("9:30 PM");
        }


    }

    /**
     *
     * @author Kevin
     */
    private void jbtnTemplateBackActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) (jPanelAdmin.getLayout());
        cl.show(jPanelAdmin, "card2");
    }

    /**
     *
     * @author Kevin
     */
    private void jbtnCourseBackActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cl = (CardLayout) (jPanelAdmin.getLayout());
        cl.show(jPanelAdmin, "card2");
    }

    /**
     *
     * @author Kevin
     */
    private void jbtnAddTemplateActionPerformed(java.awt.event.ActionEvent evt) {

        boolean exists = false;
        boolean isNewTemplate = false;

        if (!jtxtTemplateName.getText().isEmpty()) {
            Template newTemplate = new Template();

            newTemplate.setCategory((String) jcomboCategory.getSelectedItem());
            newTemplate.setCourseName((String) jcomboCourse.getSelectedItem());
            newTemplate.setTemplateName(jtxtTemplateName.getText());

            // Make sure the course hasn't already been added to a 
            // specific category
            if (jcomboCategory.getSelectedItem().equals("Natural Science")) {
                if (!scienceModel.contains(newTemplate.getCourseName())) {
                    scienceModel.add(0, (String) jcomboCourse.getSelectedItem());
                } else {
                    exists = true;
                }
            } else if (jcomboCategory.getSelectedItem().equals("Math and Stats")) {
                if (!mathStatsModel.contains(newTemplate.getCourseName())) {
                    mathStatsModel.add(0, (String) jcomboCourse.getSelectedItem());
                } else {
                    exists = true;
                }

            } else if (jcomboCategory.getSelectedItem().equals("Computer Science")) {
                if (!compsciModel.contains(newTemplate.getCourseName())) {
                    compsciModel.add(0, (String) jcomboCourse.getSelectedItem());
                } else {
                    exists = true;
                }

            } else if (jcomboCategory.getSelectedItem().equals("Humanities Writing")) {
                if (!humanitiesModel.contains(newTemplate.getCourseName())) {
                    humanitiesModel.add(0, (String) jcomboCourse.getSelectedItem());
                } else {
                    exists = true;
                }

            } else if (jcomboCategory.getSelectedItem().equals("Social Science")) {
                if (!socialModel.contains(newTemplate.getCourseName())) {
                    socialModel.add(0, (String) jcomboCourse.getSelectedItem());
                } else {
                    exists = true;
                }

            } else if (jcomboCategory.getSelectedItem().equals("Cognate Math")) {
                if (!mathModel.contains(newTemplate.getCourseName())) {
                    mathModel.add(0, (String) jcomboCourse.getSelectedItem());
                } else {
                    exists = true;
                }

            } else if (jcomboCategory.getSelectedItem().equals("General")) {
                if (!generalModel.contains(newTemplate.getCourseName())) {
                    generalModel.add(0, (String) jcomboCourse.getSelectedItem());
                } else {
                    exists = true;
                }

            } else if (jcomboCategory.getSelectedItem().equals("Elective")) {
                if (!electiveModel.contains(newTemplate.getCourseName())) {
                    electiveModel.add(0, (String) jcomboCourse.getSelectedItem());
                } else {
                    exists = true;
                }

            }

            if (exists == false) {
                roboControl.AddTemplateToDB(newTemplate);

                if (jcomboTemplate.getSelectedItem() != jtxtTemplateName.getText()) {
                    jcomboTemplate.setSelectedItem(jtxtTemplateName.getText());
                    isNewTemplate = true;
                }
                if (isNewTemplate) {
                    jcomboTemplate.addItem(jtxtTemplateName.getText());
                }
            }
        }
    }

    /**
     *
     * @author Kevin
     */
    private void ClearTemplate() {
        // Clear all the existing entries
        scienceModel.clear();
        mathStatsModel.clear();
        compsciModel.clear();
        humanitiesModel.clear();
        socialModel.clear();
        mathModel.clear();
        generalModel.clear();
        electiveModel.clear();
    }

    /**
     *
     * @author Kevin
     */
    private void jbtnTemplateSelectActionPerformed(java.awt.event.ActionEvent evt) {
        jtxtTemplateName.setText((String) jcomboTemplate.getSelectedItem());

        // Clear all the existing entries so we can add new ones.
        ClearTemplate();

        // Add all the items into their corresponding categories
        for (Template t : Template.currentTemplates) {
            if (t.getCategory().equals("Natural Science") && t.getTemplateName().equals(jtxtTemplateName.getText())) {
                scienceModel.add(0, t.getCourseName());
            } else if (t.getCategory().equals("Math and Stats") && t.getTemplateName().equals(jtxtTemplateName.getText())) {
                mathStatsModel.add(0, t.getCourseName());
            } else if (t.getCategory().equals("Computer Science") && t.getTemplateName().equals(jtxtTemplateName.getText())) {
                compsciModel.add(0, t.getCourseName());
            } else if (t.getCategory().equals("Humanities Writing") && t.getTemplateName().equals(jtxtTemplateName.getText())) {
                humanitiesModel.add(0, t.getCourseName());
            } else if (t.getCategory().equals("Social Science") && t.getTemplateName().equals(jtxtTemplateName.getText())) {
                socialModel.add(0, t.getCourseName());
            } else if (t.getCategory().equals("Cognate Math") && t.getTemplateName().equals(jtxtTemplateName.getText())) {
                mathModel.add(0, t.getCourseName());
            } else if (t.getCategory().equals("General") && t.getTemplateName().equals(jtxtTemplateName.getText())) {
                generalModel.add(0, t.getCourseName());
            } else if (t.getCategory().equals("Elective") && t.getTemplateName().equals(jtxtTemplateName.getText())) {
                electiveModel.add(0, t.getCourseName());
            }
        }
    }

    /**
     * @author Kevin
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoboAdvisorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoboAdvisorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoboAdvisorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoboAdvisorAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                RoboAdvisorAdmin admin = new RoboAdvisorAdmin();
                admin.setVisible(true);
                admin.setDefaultCloseOperation(HIDE_ON_CLOSE);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDays;
    private javax.swing.ButtonGroup buttonGroupSemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAdmin;
    private javax.swing.JPanel jPanelAdminCourse;
    private javax.swing.JPanel jPanelAdminMain;
    private javax.swing.JPanel jPanelAdminTemplate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton jbtnAddTemplate;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnClearCourse;
    private javax.swing.JButton jbtnCourseAdmin;
    private javax.swing.JButton jbtnCourseBack;
    private javax.swing.JButton jbtnDeleteCourse;
    private javax.swing.JButton jbtnEditCourse;
    private javax.swing.JButton jbtnSaveCourse;
    private javax.swing.JButton jbtnTemplateAdmin;
    private javax.swing.JButton jbtnTemplateBack;
    private javax.swing.JButton jbtnTemplateSelect;
    private javax.swing.JComboBox jcomboCategory;
    private javax.swing.JComboBox jcomboCourse;
    private javax.swing.JComboBox jcomboEdit;
    private javax.swing.JComboBox jcomboTemplate;
    private javax.swing.JComboBox jcomboTime;
    private javax.swing.JLabel jlblAdminDesc;
    private javax.swing.JLabel jlblAdminTitle;
    private javax.swing.JLabel jlblCRN;
    private javax.swing.JLabel jlblCategory;
    private javax.swing.JLabel jlblCourse;
    private javax.swing.JLabel jlblCourseCreationTitle;
    private javax.swing.JLabel jlblCourseName;
    private javax.swing.JLabel jlblCourseTitle;
    private javax.swing.JLabel jlblDays;
    private javax.swing.JLabel jlblDescription;
    private javax.swing.JLabel jlblProfessor;
    private javax.swing.JLabel jlblSemester;
    private javax.swing.JLabel jlblTemplateTitle;
    private javax.swing.JList jlistCompsci;
    private javax.swing.JList jlistElectives;
    private javax.swing.JList jlistGeneral;
    private javax.swing.JList jlistHumanities;
    private javax.swing.JList jlistMath;
    private javax.swing.JList jlistMathStats;
    private javax.swing.JList jlistScience;
    private javax.swing.JList jlistSocial;
    private javax.swing.JRadioButton jradJanMay;
    private javax.swing.JRadioButton jradMWF;
    private javax.swing.JRadioButton jradSeptDec;
    private javax.swing.JRadioButton jradTR;
    private javax.swing.JTable jtblPrereq;
    private javax.swing.JTextField jtxtCRN;
    private javax.swing.JTextField jtxtCourseName;
    private javax.swing.JTextField jtxtCourseTitle;
    private javax.swing.JTextArea jtxtDescription;
    private javax.swing.JTextField jtxtProfessor;
    private javax.swing.JTextField jtxtTemplateName;
    // End of variables declaration//GEN-END:variables
}

/**
 *
 * @author Kevin
 */
class NewTableModel extends DefaultTableModel {

    public NewTableModel() {
    }

    @Override
    public Class getColumnClass(int col) {
        if (col == 0) {
            return Boolean.class;
        } else {
            return String.class;
        }
    }

    @Override
    public boolean isCellEditable(int row, int col) {
        if (col == 1) {
            return false;
        }
        if (col == 2) {
            return false;
        } else {
            return true;
        }
    }
}